---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  ttlSecondsAfterEmpty: 300
  ttlSecondsUntilExpired: 259200
  limits:
    resources:
      cpu: 20
  requirements:
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values: ["t3", "t3a", "t2"]
    - key: karpenter.k8s.aws/instance-size
      operator: "In"
      values: ["micro", "small"]
  providerRef:
    name: my-provider
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: my-provider
spec:
  subnetSelector:
    kubernetes.io/cluster/dev-cluster: owned
  securityGroupSelector:
    kubernetes.io/cluster/dev-cluster: owned
