---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  ttlSecondsAfterEmpty: 60 # scale down nodes after 60 seconds without workloads (excluding daemons)
  ttlSecondsUntilExpired: 604800 # expire nodes after 7 days (in seconds) = 7 * 60 * 60 * 24
  limits:
    resources:
      cpu: 100
  requirements:
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values: [nano, micro, small, large]
    - key: karpenter.k8s.aws/instance-size
      operator: NotIn
      values: [c5, m5, r5]
  providerRef:
    name: my-provider
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: my-provider
spec:
  subnetSelector:
    kubernetes.io/cluster/dev-cluster: owned
  securityGroupSelector:
    kubernetes.io/cluster/dev-cluster: owned
